#!/bin/bash

if [ -f "/provisioning" ]
then
  echo "Container is still provisioning itself."
  exit 1
fi
if [ ! -f /var/run/nginx.pid ]
then
  echo "nginx is not running."
  exit 2
fi
if [ ! -f /var/run/supervisord.pid ]
then
  echo "supervisor is not running."
  exit 2
fi
