#!/bin/bash

THRESHOLD=${HEALTHCHECK_TIMEOUT:-300};

COUNTER=0;
until [ healthcheck ]
do
  echo "Wait for container to be healthy..."
  (( COUNTER++));
  if (( COUNTER > THRESHOLD ))
  then
    echo ""
    echo "Error: container seems to provision for longer than $THRESHOLD seconds."
    echo "Either check what takes so long or consider raising \$HEALTHCHECK_TIMEOUT."
    exit 1
  fi
  sleep 1
done

echo "container ready."
