ENV PROJECT_ROOT /var/www
ENV PROJECT_WEBROOT /var/www/public
ENV PROJECT_BINARIES /var/www/bin
ENV GLOBAL_BINARIES /usr/local/bin

ENV PATH $PATH:$PROJECT_BINARIES:$GLOBAL_BINARIES

RUN mkdir -p $PROJECT_ROOT && mkdir -p $GLOBAL_BINARIES

WORKDIR $PROJECT_ROOT