name: Build active images (scheduled)
on:
  schedule:
    - cron: "0 10 * * 0" # every sunday at 10am
  workflow_dispatch:

jobs:
  update-image:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - base: cli
            php_version: "8.0"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:cli-8.0'
          - base: cli
            php_version: "8.1"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:cli-8.1'
          - base: cli
            php_version: "8.2"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:cli-8.2,phpimageleague/php-application-server:cli-8,phpimageleague/php-application-server:cli'
          - base: fpm
            php_version: "8.0"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:fpm-8.0,phpimageleague/php-application-server:web-8.0'
          - base: fpm
            php_version: "8.1"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:fpm-8.1,phpimageleague/php-application-server:web-8.1'
          - base: fpm
            php_version: "8.2"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:fpm-8.2,phpimageleague/php-application-server:web-8.2,phpimageleague/php-application-server:fpm-8,phpimageleague/php-application-server:web-8,phpimageleague/php-application-server:fpm,phpimageleague/php-application-server:web,phpimageleague/php-application-server:latest'
          - base: swoole
            php_version: "8.0"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:swoole-8.0'
          - base: swoole
            php_version: "8.1"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:swoole-8.0'
          - base: swoole
            php_version: "8.2"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:swoole-8.2,phpimageleague/php-application-server:swoole-8,phpimageleague/php-application-server:swoole'
          - base: fpm-dev
            php_version: "8.0"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:fpm-dev-8.0,phpimageleague/php-application-server:dev-8.0'
          - base: fpm-dev
            php_version: "8.1"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:fpm-dev-8.1,phpimageleague/php-application-server:dev-8.1'
          - base: fpm-dev
            php_version: "8.2"
            arches: linux/amd64,linux/arm64
            tags: 'phpimageleague/php-application-server:fpm-dev-8.2,phpimageleague/php-application-server:dev-8.2,phpimageleague/php-application-server:fpm-dev-8,phpimageleague/php-application-server:dev-8,phpimageleague/php-application-server:fpm-dev,phpimageleague/php-application-server:dev'
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: 'main'
      -
        name: Pre process Dockerfile
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          BASE: ${{ matrix.base }}
        run: ./preprocessor "$BASE.Dockerfile" > Dockerfile
      -
        name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: "PHP_VERSION=${{ matrix.php_version }}"
          platforms: ${{ matrix.arches }}
          tags: ${{ matrix.tags }}
          push: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
